### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by datakurre** [epeli/react-starter#1]
Sounds like public domain, but adding explicit mention about it would be nice.

**Comment by esamattis** [comment]
yeah it should be!

**Comment by esamattis** [comment]
Good? https://github.com/epeli/react-starter/pull/2

**Comment by datakurre** [comment]
:+1:

Esa-Matti Suuronen kirjoitti ti joulukuuta 22 09:28:10 2015 GMT+0200:
